---

- name: MnoHub | Release folder
  set_fact: release_folder="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"

- name: MnoHub | Download application from S3 (mnohub-XXX.tar.gz)
  s3:
    bucket: "{{ mno_pkgs_bucket }}"
    object: "mnohub/{{ mnohub_folder }}/{{ mnohub_version }}.tar.gz"
    dest: "{{ deploy_directory }}/{{ mnohub_version }}.tar.gz"
    mode: get
    region: "{{ mno_pkgs_s3_aws_region }}"
    aws_access_key: "{{ mno_pkgs_s3_aws_access_key }}"
    aws_secret_key: "{{ mno_pkgs_s3_aws_secret_key }}"

- name: MnoHub | Replace version
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}"
    state: absent

- name: MnoHub | Create version directory (/apps/mnohub/releases/XXX)
  file: path={{ deploy_directory }}/releases/{{ release_folder }} owner=deployer group=deployer state=directory

- name: MnoHub | Extract current version
  command: "tar -xzf {{ deploy_directory }}/{{ mnohub_version }}.tar.gz -C {{ deploy_directory }}/releases/{{ release_folder }}"

- name: MnoHub | Clean up tar file
  file:
    path: "{{ deploy_directory }}/{{ mnohub_version }}.tar.gz"
    state: absent

- name: MnoHub | Clean up gems
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/bundle"
    state: absent

- name: MnoHub | Clean up gems
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor"
    state: directory

- name: MnoHub | Database file config/database.yml
  template:
    src: database.yml
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/database.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: MnoHub | Configuration file shared/config/application.yml
  template:
    src: application.yml
    dest: "{{ deploy_directory }}/shared/config/application.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: MnoHub | Delete existing link for config/application.yml
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/config/application.yml"
    state: absent

- name: MnoHub | Symbolic link to config/application.yml
  file:
    src: "{{ deploy_directory }}/shared/config/application.yml"
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/application.yml"
    owner: deployer
    group: deployer
    state: link
    force: yes

- name: MNO Hub | Clean directory for Xero API certificates
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/xero-certs"
    state: absent
    owner: deployer
    group: deployer
    mode: 0755
  tags: [xero]

- name: MNO Hub | Clean directory for Xero API certificates
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/xero-certs/{{ rails_environment }}"
    state: directory
    owner: deployer
    group: deployer
    mode: 0755
  tags: [xero]

- name: MnoHub | Directory for Xero API certificates
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/xero-certs/{{ rails_environment }}"
    state: directory
    owner: deployer
    group: deployer
    mode: 0755
  tags: [xero]

- name: MnoHub | Deploy Xero API certificates
  copy:
    content: "{{ lookup('file', 'files/xero_certs/' + environment_name + '/' + rails_environment + '/' + item) }}"
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/xero-certs/{{ rails_environment }}/{{ item }}"
    owner: deployer
    group: deployer
    mode: 0755
  with_items:
    - privatekey.pem
    - entrust-cert.pem
    - entrust-private-nopass.pem
  tags: [xero]

- name: MnoHub | Set directory permissions
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}"
    mode: 0755
    owner: deployer
    group: deployer
    state: directory
    recurse: yes

- name: MnoHub | Symbolic link to gems
  file:
    src: "{{ deploy_directory }}/shared/vendor_bundle"
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/bundle"
    owner: deployer
    group: deployer
    state: link
    force: yes

- name: MnoHub | Configure settings file
  template:
    src: settings_environment.yml
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/settings/{{ rails_environment }}.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: MnoHub | Run bundle install
  command: "chdir={{ deploy_directory }}/releases/{{ release_folder }} /opt/jruby/current/bin/jruby -S bundle install --path={{ deploy_directory }}/shared/vendor_bundle --gemfile={{ deploy_directory }}/releases/{{ release_folder }}/Gemfile --deployment --without development test"
  sudo_user: deployer

- name: MNO Hub | Migrate the database
  command: "chdir={{ deploy_directory }}/releases/{{ release_folder }} bundle exec rake db:migrate_or_setup"
  environment: "{{ default_environment }}"
  sudo_user: deployer
  when: not mnohub_config.skip_migrations

- name: MnoHub | Assets precompile
  command: "chdir={{ deploy_directory }}/releases/{{ release_folder }} /opt/jruby/current/bin/jruby -S bundle exec rake assets:precompile"
  sudo_user: deployer
  environment: "{{ default_environment }}"

- name: MnoHub | Replace previous version
  file:
    path: "{{ deploy_directory }}/current"
    state: absent

- name: MnoHub | Symbolic link to current version
  file:
    src: "{{ deploy_directory }}/releases/{{ release_folder }}"
    dest: "{{ deploy_directory }}/current"
    owner: deployer
    group: deployer
    state: link
    force: yes

- name: MnoHub | Clean directories
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/{{ item }}"
    state: absent
  with_items:
    - log
    - tmp
    - solr
    - geocoder
    - downloads

- name: MnoHub | Symbolic links to shared directories
  file:
    src: "{{ deploy_directory }}/shared/{{ item }}"
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/{{ item }}"
    owner: deployer
    group: deployer
    state: link
    force: yes
  with_items:
    - log
    - tmp
    - solr
    - geocoder
    - downloads
