{% if mnohub_config.general.organization_initial_credit is defined %}
organization_initial_credit: {{ mnohub_config.general.organization_initial_credit }}
{% endif %}
{% if mnohub_config.billing is defined %}
billing:
  billing_currencies: {{ mnohub_config.billing.currencies }}
  default_billing_currency: {{ mnohub_config.billing.default_currency }}
{% endif %}
background_job:
  disable_recurring_jobs: {{ mnohub_config.background_jobs_disabled }}
sso:
  virtual_email_domain: {{ mnohub_config.general.virtual_email_domain }}
  delegation_idp: {{ mnohub_config.sso_idp_delegation }}
contact:
  support: {{ mnohub_config.general.support_email }}
mcluster:
  host: {{ mnohub_config.general.nex_host }}
  apps_domain: {{ mnohub_config.general.apps_domain }}
  fallback_region: {{ mnohub_config.general.fallback_region }}
  mnoe_lockdown_region: {{ mnohub_config.general.mnoe_lockdown_region }}
  autostop_disabled: {{ mnohub_config.mcluster_autostop_disabled }}
encryption:
  key: <%= ENV['encryption_key'] %>
connec:
  protocol: {{ connec_config.private_dns.scheme }}
  host: {{ connec_config.private_dns.host }}
  port: {{ 443 if connec_config.private_dns.scheme == 'https' else 80 }}
  authentication:
    key: <%= ENV['connec_authentication_key'] %>
    secret: <%= ENV['connec_authentication_secret'] %>
  paths:
    sync: /v1/:instance_uid/sync
    all_accounts: /api/reports/:org_uid/account_balances
    balance_sheet: /api/reports/:channel/balance_sheet
    accounts_summary: /api/reports/:channel/accounts_summary
    customers_invoices: /api/reports/:channel/customers_invoices
    suppliers_invoices: /api/reports/:channel/suppliers_invoices
  upload:
    protocol: {{ connec_config.private_dns.scheme }}
    company: {{ connec_config.private_dns.host }}/v1/:channel_id/company
    organizations: {{ connec_config.private_dns.host }}/v1/admin/uploads/organizations
    people: {{ connec_config.private_dns.host }}/v1/admin/uploads/people
    items: {{ connec_config.private_dns.host }}/v1/admin/uploads/items
oauth:
  {{ connec_config.oauth | to_json }}
carrierwave:
  region: ap-southeast-1 # irrelevant - S3 is not region specific
  public_bucket: {{ mnohub_config.carrierwave.public_bucket }}
  private_bucket: {{ mnohub_config.carrierwave.private_bucket }}
  asset_host: {{ mnohub_config.carrierwave.asset_host }}
microsoft:
  partner_id: 000000
geocoder:
  lookup: 'google'
  ip_lookup: 'geoip2'
  geoip2:
    file: <%= File.join(Rails.root,'geocoder','geodb.mmdb') %>

# Developer platform
dev_platform:
  url: <%= ENV['DEV_PLATFORM_ENDPOINT'] %>
