---
#=======================================================================
#=======================================================================
# Encrypted Secrets
#=======================================================================
#=======================================================================
# This file must be encrypted using Ansible Vault

#=======================================================================
#=======================================================================
# AWS Keys
#=======================================================================
#=======================================================================
# These keys are used by the EC2 instances to retrieve applications packages
# such as Connec!, Impac! etc. from the 'mnoe-packages' S3 bucket
# To be provided by Maestrano
mno_pkgs_bucket:
mno_pkgs_s3_aws_access_key:
mno_pkgs_s3_aws_secret_key:
mno_pkgs_s3_aws_region:

# These keys are used by the EC2 instances to fetch the configured deployment scripts.
# It should be using the tenant AWS account and S3 bucket
tenant_dropbox_s3_aws_access_key:
tenant_dropbox_s3_aws_secret_key:
tenant_dropbox_s3_aws_region:
mno_deploy_configuration_bucket:
mno_deploy_configuration_path:

# These keys are used to (de)register instances from ELBs during deployments
# It needs to have EC2 ELB access to the targeted AWS account
infra_ec2_aws_access_key:
infra_ec2_aws_access_secret:
infra_ec2_aws_region:

#=======================================================================
#=======================================================================
# General Environment configuration
#=======================================================================
#=======================================================================
# New Relic
newrelic_license_key: # Set your New Relic license key
newrelic_app_name: My Environment

#=======================================================================
#=======================================================================
# Infrastructure configuration
#=======================================================================
#=======================================================================
# RDS database for MNO Hub, MCluster and any required frontend
rds:
  username: root
  password: changeme

#=======================================================================
#=======================================================================
# Application Configuration
#=======================================================================
#=======================================================================

# MongoDB
mongodb_user_admin_name: siteUserAdmin
mongodb_user_admin_password: changeme
mongodb_root_admin_name: siteRootAdmin
mongodb_root_admin_password: changeme

# Connec Database
mongodb_user_connec: connec
mongodb_password_connec: changeme
mongodb_database_connec: connec

# Nex database credentials
nex_database_name: mcluster
nex_database_username: mcluster
nex_database_password: changeme

# Maestrano Enterprise database credentials
mnoe_database_name: mnoe
mnoe_database_username: mnoe
mnoe_database_password: changeme

# Enterprise Frontend configuration
frontend_config:
  extra_variables:
    SECRET_KEY_BASE: changeme
    MANDRILL_API_KEY: changeme
    tenant_id: changeme # Provided by Maestrano
    tenant_key: changeme # Provided by Maestrano

# Maestrano configuration
mnohub_config:
  database:
    username: maestrano
    password: changeme
  default_tenant:
    id: changeme # Provided by Maestrano
    key: changeme # Provided by Maestrano
  secrets:
    encryption_key: changeme
    open_exchange_rate_id: changeme
  s3_bucket:
    access_key: changeme # S3 bucket used for assets management
    secret_access_key: changeme

# Connec! configuration
connec_config:
  authentication:
    admin:
      client_id: changeme
      client_key: changeme
  oauth:
    xero:
      key: changeme # Use your Xero OAuth keys
      secret: changeme # Use your Xero OAuth keys
      endpoint: https://api-partner.network.xero.com/api.xro/2.0
      site: https://api-partner.network.xero.com
      private_key: vendor/xero-certs/uat/privatekey.pem
      ssl_client_cert: vendor/xero-certs/uat/entrust-cert.pem
      ssl_client_key: vendor/xero-certs/uat/entrust-private-nopass.pem
      signature_method: RSA-SHA1
      user_agent: Maestrano UAT
    quickbooks:
      credentials:
        default:
          key: changeme # Set your QBO OAuth keys
          secret: changeme # Set your QBO OAuth keys
      api_endpoint: https://sandbox-quickbooks.api.intuit.com
      site: https://oauth.intuit.com
      login_endpoint: https://oauth.intuit.com
      request_token_path: /oauth/v1/get_request_token
      authorize_url: https://appcenter.intuit.com/Connect/Begin
      access_token_path: /oauth/v1/get_access_token
    myob:
      key: changeme # Set your MYOB OAuth keys
      secret: changeme # Set your MYOB OAuth keys
    eventbrite:
      key: changeme # Set your Eventbrite OAuth keys
      secret: changeme # Set your Eventbrite OAuth keys
