---

- name: Nex! | Install packages
  apt: "name={{ item }} state=present update_cache=yes"
  with_items:
    - curl
    - libcurl3
    - libcurl3-gnutls
    - libcurl4-openssl-dev
    - libmysqlclient-dev
    - libsqlite3-dev
    - nodejs
  when: ansible_os_family == "Debian"

- name: Nex! | Install packages
  yum: "name={{ item }} state=present update_cache=yes"
  with_items:
    - curl
    - nodejs
  when: ansible_os_family == "RedHat"

- name: Nex! | Create deployment user
  user: name=deployer comment="Application deployment user"

- name: Nex! | Add deployer user to sudoers
  lineinfile: dest=/etc/sudoers regexp="deployer ALL" line="deployer ALL=(ALL) NOPASSWD:ALL" state=present

- name: Nex! | Create deployment directory
  file: path={{deploy_directory}} owner=deployer group=deployer state=directory

- name: Nex! | Make shared directories
  file: path={{deploy_directory}}/shared/{{item}} group=deployer owner=deployer state=directory
  with_items:
    - tmp
    - log
    - public
    - bundle
    - bin
    - config
    - pids
    - sockets
    - vendor_bundle
    - downloads
    - geocoder
    - solr
    - assets
    - styles
    - scripts

- name: Nex! | Install bundler
  command: gem install bundler

- name: Nex! | Install puma
  command: gem install puma

- include: puma_deb.yml
  when: ansible_os_family == "Debian"

- include: puma_rhel.yml
  when: ansible_os_family == "RedHat"

- name: Nex! | Copy puma.rb config
  template: src=puma.rb dest={{deploy_directory}}/shared/config/puma.rb owner=deployer group=deployer mode=0755

- name: Nex! | Nginx default site deactivation
  file: path=/etc/nginx/sites-enabled/default.conf state=absent

- name: Nex! | Nginx site configuration
  template: src=etc-nginx-nex dest=/etc/nginx/sites-available/nex
  register: nginxconfig

- name: Nex! | Nginx certificates directory
  file: path=/etc/nginx/certificates state=directory
  when: ssl_internal_cert is defined and ssl_internal_key is defined

- name: Nex! | Nginx SSL Certificate
  template: src=etc-nginx-nex-ssl-cert dest=/etc/nginx/certificates/nex.crt
  register: nginxsslcert
  when: ssl_internal_cert is defined and ssl_internal_key is defined

- name: Nex! | Nginx SSL Certificate Key
  template: "src=etc-nginx-nex-ssl-key dest=/etc/nginx/certificates/nex.key"
  register: nginxsslkey
  when: ssl_internal_cert is defined and ssl_internal_key is defined

- name: Nex! | Nginx site activation
  file:
    src: "/etc/nginx/sites-available/nex"
    dest: "/etc/nginx/sites-enabled/nex"
    state: link
    force: yes

- name: Nex! | Nginx restart
  shell: service nginx restart
  when: nginxconfig.changed or (nginxsslcert is defined and nginxsslcert.changed) or (nginxsslkey is defined and nginxsslkey.changed)

- name: Nex! | Configure splunk forwarder inputs
  shell: "/opt/splunkforwarder/bin/splunk add monitor {{ item.monitor }} -index {{ item.index }} -hostname {{ ansible_hostname }} -auth {{ splunk.username }}:{{ splunk.password }}"
  when: not splunk.skip
  with_items: "{{ splunk.nex.inputs }}"
  tags: [splunk-configure]
  ignore_errors: true
