---

- name: Connec | Release folder
  set_fact: release_folder="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"

- name: Connec | Download application from S3
  s3:
    bucket: "{{ mno_pkgs_bucket }}"
    object: "connec/{{ connec_folder }}/{{ connec_version }}.tar.gz"
    dest: "{{ deploy_directory }}/{{ connec_version }}.tar.gz"
    mode: get
    region: "{{ mno_pkgs_s3_aws_region }}"
    aws_access_key: "{{ mno_pkgs_s3_aws_access_key }}"
    aws_secret_key: "{{ mno_pkgs_s3_aws_secret_key }}"

- name: Connec | Replace version
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}"
    state: absent

- name: Connec | Create version directory (/apps/connec/releases/XXX)
  file: path={{ deploy_directory }}/releases/{{ release_folder }} owner=deployer group=deployer state=directory

- name: Connec | Extract current version
  command: "tar -xzf {{ deploy_directory }}/{{ connec_version }}.tar.gz -C {{ deploy_directory }}/releases/{{ release_folder }}"

- name: Connec | Clean up tar file
  file:
    path: "{{ deploy_directory }}/{{ connec_version }}.tar.gz"
    state: absent

- name: Connec | Clean up gems
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/bundle"
    state: absent

- name: Connec | Clean up gems
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor"
    state: directory

- name: Connec | Database file database.yml
  template:
    src: database.yml
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/database.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: Connec | MongoDB file mongoid.yml
  template:
    src: mongoid.yml
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/mongoid.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: Connec | NewRelic file newrelic.yml
  template:
    src: newrelic.yml
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/newrelic.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: Connec | Sidekiq sidekiq.yml
  template:
    src: sidekiq.yml
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/sidekiq.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: Connec | Configuration file config/application.yml
  template:
    src: application.yml
    dest: "{{ deploy_directory }}/shared/config/application.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: Connec | Replace config/application.yml
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/config/application.yml"
    state: absent

- name: Connec | Symbolic link to config/application.yml
  file:
    src: "{{ deploy_directory }}/shared/config/application.yml"
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/application.yml"
    owner: deployer
    group: deployer
    state: link
    force: yes

- name: Connec | Clean directory for Xero API certificates
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/xero-certs"
    state: absent
    owner: deployer
    group: deployer
    mode: 0755
  tags: [xero]

- name: Connec | Clean directory for Xero API certificates
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/xero-certs/{{ rails_environment }}"
    state: directory
    owner: deployer
    group: deployer
    mode: 0755
  tags: [xero]

- name: Connec | Deploy Xero API certificates
  copy:
    content: "{{ lookup('file', 'files/xero_certs/' + environment_name + '/' + rails_environment + '/' + item) }}"
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/xero-certs/{{ rails_environment }}/{{ item }}"
    owner: deployer
    group: deployer
    mode: 0755
  with_items:
    - privatekey.pem
    - entrust-cert.pem
    - entrust-private-nopass.pem
  tags: [xero]

- name: Connec | Symbolic link to log directory
  file:
    src: "{{ deploy_directory }}/shared/log"
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/log"
    owner: deployer
    group: deployer
    state: link
    force: yes

- name: Connec | Set log directory permissions
  file:
    path: "{{ deploy_directory }}/shared/log"
    mode: 0755
    owner: deployer
    group: deployer
    state: directory
    recurse: yes

- name: Connec | Set directory permissions
  file:
    path: "{{ deploy_directory }}/releases/{{ release_folder }}"
    mode: 0755
    owner: deployer
    group: deployer
    state: directory
    recurse: yes

- name: Connec | Symbolic link to gems
  file:
    src: "{{ deploy_directory }}/shared/vendor_bundle"
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/vendor/bundle"
    owner: deployer
    group: deployer
    state: link
    force: yes

- name: Connec | Configure settings file
  template:
    src: settings_environment.yml
    dest: "{{ deploy_directory }}/releases/{{ release_folder }}/config/settings/{{ rails_environment }}.yml"
    owner: deployer
    group: deployer
    mode: 0755

- name: Connec | Run bundle install
  command: "chdir={{ deploy_directory }}/releases/{{ release_folder }} /opt/jruby/current/bin/jruby -S bundle install --path={{ deploy_directory }}/shared/vendor_bundle --gemfile={{ deploy_directory }}/releases/{{ release_folder }}/Gemfile --deployment --without development test"
  sudo_user: deployer

- name: Connec | Update MongoDB indexes
  command: "chdir={{ deploy_directory }}/releases/{{ release_folder }} bundle exec rake db:mongoid:create_indexes"
  environment: "{{ default_environment }}"
  sudo_user: deployer

- name: Connec | Run data migrations
  command: "chdir={{ deploy_directory }}/releases/{{ release_folder }} bundle exec rake mongoid:migrate"
  environment: "{{ default_environment }}"
  sudo_user: deployer

- name: Connec | Replace previous version
  file:
    path: "{{ deploy_directory }}/current"
    state: absent

- name: Connec | Symbolic link to current version
  file:
    src: "{{ deploy_directory }}/releases/{{ release_folder }}"
    dest: "{{ deploy_directory }}/current"
    owner: deployer
    group: deployer
    state: link
    force: yes
