# Production secrets

# Development configuration
# This file is used to store any sensible configuration parameter
#
# Configuration parameters are stored in the ENV global variable
# E.g. ENV['mandrill_username']
#

# Rails Secret
SECRET_KEY_BASE: "{{ nex_config.rails_secret_key }}"

# Github OAuth Configuration
GITHUB_OAUTH_KEY: "{{ nex_config.github.oauth_key }}"
GITHUB_OAUTH_SECRET: "{{ nex_config.github.oauth_secret }}"

# NewRelic Configuration
newrelic_license_key: "{{ newrelic_license_key }}"
newrelic_app_name: "core-nex-{{ rails_environment }}"

# Main email service
# Emails blocked at Mandrill level in development (can be seen in outbound dashboard)
mandrill_username: "{{ nex_config.mandrill.login }}"
mandrill_key: "{{ nex_config.mandrill.token }}"

# AWS Credentials - Infrastructure Management
aws_access_key_id: "{{ nex_config.aws.access_key }}"
aws_secret_access_key: "{{ nex_config.aws.secret_access_key }}"

# Mandrill - Used to configure SMTP Relay on ComputeRacks
# (emails sent by the applications)
grid_mandrill_login: {{ nex_config.mandrill_grid.login }}
grid_mandrill_token: {{ nex_config.mandrill_grid.token }}

# Storage Rsync Key - Used to authenticate ComputeRack on
# StorageRacks when pushing/pulling cubes
storage_rsync_key: "{{ nex_config.storage_rsync_key }}"

# SSH Keys
{% for key, value in nex_config.ssh_keys.iteritems() %}
{{ key }}: "{{ value }}"
{% endfor %}

# SSL Certificate
ssl_cert_key_cube_default: "{{ nex_config.ssl.cert_key_cube_default }}"
ssl_cert_chained_cube_default: "{{ nex_config.ssl.cert_chained_cube_default }}"

# Routing Grid credentials
routing_grid_key: "{{ nex_config.routing.key }}"
routing_grid_secret: "{{ nex_config.routing.secret }}"

# Compute Grid credentials
compute_grid_key: "{{ nex_config.compute.key }}"
compute_grid_secret: "{{ nex_config.compute.secret }}"

# VPN Key
vpn_key: "{{ nex_config.vpn_key }}"
